export const NEWS_LIST_REQUEST = "NEWS_LIST_REQUEST";
export const NEWS_LIST_SUCCESS = "NEWS_LIST_SUCCESS";
export const NEWS_LIST_FAIL = "NEWS_LIST_FAIL";

export const NEWS_COUNTRY_LIST_REQUEST = "NEWS_COUNTRY_LIST_REQUEST";
export const NEWS_COUNTRY_LIST_SUCCESS = "NEWS_COUNTRY_LIST_SUCCESS";
export const NEWS_COUNTRY_LIST_FAIL = "NEWS_COUNTRY_LIST_FAIL";

export const NEWS_SEARCH_LIST_REQUEST = "NEWS_SEARCH_LIST_REQUEST";
export const NEWS_SEARCH_LIST_SUCCESS = "NEWS_SEARCH_LIST_SUCCESS";
export const NEWS_SEARCH_LIST_FAIL = "NEWS_SEARCH_LIST_FAIL";
